'use client';
import { useEffect,useState } from 'react';
import Link from 'next/link';
import { CardSurface } from '@/components/city/CityFoundation';
import { formatArea,formatCurrency,formatDate,formatInteger } from '@/lib/utils';

export function AccountWorkspace({locale,section}:{locale:string;section:string}){
  const ar=locale==='ar';
  const [data,setData]=useState<any>(null),[page,setPage]=useState(1),[error,setError]=useState(''),[selection,setSelection]=useState<string[]>([]),[comparison,setComparison]=useState<any[]>([]),[busy,setBusy]=useState(false);
  const unavailable=ar?'تعذر تحميل البيانات. حاول مجدداً.':'Chargement indisponible. Réessayez.';
  async function load(){setError('');try{const response=await fetch(`/api/account?page=${page}`,{cache:'no-store'});if(response.status===401){window.location.assign(`/${locale}/auth/login?next=${encodeURIComponent(`/${locale}/account/${section}`)}`);return;}if(!response.ok)throw new Error();setData(await response.json());}catch{setError(unavailable);}}
  useEffect(()=>{void load();},[page,section]); // eslint-disable-line react-hooks/exhaustive-deps
  async function logout(all=false){setBusy(true);try{const r=await fetch('/api/auth/logout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({locale,all})});if(!r.ok)throw new Error();window.location.assign(`/${locale}`);}catch{setError(unavailable);}finally{setBusy(false);}}
  async function compare(){setBusy(true);try{const response=await fetch('/api/account/compare',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({items:selection.map(value=>{const [kind,id]=value.split(':');return {kind,id};})})});if(!response.ok)throw new Error();setComparison((await response.json()).rows);}catch{setError(unavailable);}finally{setBusy(false);}}
  const toggle=(value:string)=>setSelection(current=>current.includes(value)?current.filter(item=>item!==value):current.length<6?[...current,value]:current);
  if(error)return <CardSurface className="p-6"><p role="alert">{error}</p><button className="mt-4 min-h-11 text-brand-blue" onClick={load}>{ar?'إعادة المحاولة':'Réessayer'}</button></CardSurface>;
  if(!data)return <p role="status" className="py-10">{ar?'جارٍ التحميل…':'Chargement…'}</p>;
  const empty=ar?'لا توجد عناصر بعد. ابدأ بتقدير عقارك الأول.':'Votre espace est prêt. Commencez par estimer votre premier bien.';
  const estimationLink=`/${locale}/cities/casablanca/estimate`;
  const eventCard=(event:any,selectable=false)=><CardSurface className="p-5" key={event.id}>
    {selectable?<label className="mb-3 flex min-h-11 items-center gap-3 text-sm"><input type="checkbox" checked={selection.includes(`estimation:${event.id}`)} onChange={()=>toggle(`estimation:${event.id}`)}/>{ar?'اختيار التقدير':'Sélectionner l’estimation'}</label>:null}
    <p className="text-xs text-text-muted">{formatDate(event.created_at,locale)} · {event.city?.name}</p><h3 className="mt-2 font-bold">{event.input_features.neighborhood} · {event.input_features.property_type}</h3><p className="mt-2 text-xl font-bold text-brand-blue">{formatCurrency(Number(event.estimated_price_mad),locale)}</p><p className="mt-2 text-xs text-text-secondary">{formatArea(event.input_features.area,locale)} · {event.model_version}</p><Link className="mt-3 inline-flex min-h-11 items-center text-sm text-brand-blue" href={`/${locale}/account/estimations/${event.id}`}>{ar?'فتح الجواز':'Ouvrir le Passeport'}</Link>
  </CardSurface>;
  return <div className="space-y-6">
    {!section?<><p className="text-text-secondary">{ar?'مرحباً':'Bienvenue'}{data.profile.display_name?`, ${data.profile.display_name}`:''}.</p><div className="grid gap-4 sm:grid-cols-3">{[[ar?'التقديرات المحفوظة':'Estimations sauvegardées',data.eventCount],[ar?'العقارات المحفوظة':'Biens enregistrés',data.propertyCount],[ar?'الجوازات العقارية':'Passeports immobiliers',data.passportCount]].map(([label,value])=><CardSurface key={label} className="p-6"><p className="text-sm text-text-secondary">{label}</p><p className="mt-2 text-3xl font-bold">{formatInteger(value,locale)}</p></CardSurface>)}</div>{data.events[0]?eventCard(data.events[0]):<CardSurface className="p-6">{empty}</CardSurface>}<div className="flex flex-wrap gap-5 text-brand-blue"><Link className="inline-flex min-h-11 items-center" href={estimationLink}>{ar?'تقدير عقار':'Estimer un bien'}</Link>{data.events[0]?.city?.slug==='casablanca'?<Link className="inline-flex min-h-11 items-center" href={`/${locale}/cities/casablanca/market`}>{ar?'سوق الدار البيضاء':'Marché de Casablanca'}</Link>:null}</div></>:null}
    {section==='estimations'?<><h2 className="text-xl font-bold">{ar?'تقديراتي':'Mes estimations'}</h2><div className="grid gap-4 lg:grid-cols-2">{data.events.map((event:any)=>eventCard(event))}</div>{!data.events.length?<p>{empty}</p>:null}</>:null}
    {section==='properties'?<><h2 className="text-xl font-bold">{ar?'عقاراتي':'Mes biens'}</h2>{data.properties.length?<div className="grid gap-4 lg:grid-cols-2">{data.properties.map((property:any)=><PropertyCard key={property.id} property={property} locale={locale} refresh={load}/>)}</div>:<p>{ar?'يمكنك حفظ عقار من جوازك العقاري بعد التقدير.':'Enregistrez un bien depuis son Passeport après une estimation.'}</p>}</>:null}
    {section==='passports'?<><h2 className="text-xl font-bold">{ar?'جوازاتي العقارية':'Mes Passeports immobiliers'}</h2><p className="text-sm leading-6 text-text-secondary">{ar?'يُنشأ الجواز من تقدير حقيقي محفوظ، ولا نعرض أي بيانات افتراضية.':'Chaque Passeport provient d’une estimation réellement enregistrée ; aucune donnée fictive n’est affichée.'}</p><div className="grid gap-4 lg:grid-cols-2">{data.events.map((event:any)=>eventCard(event))}</div>{!data.events.length?<CardSurface className="p-6">{ar?'لا يوجد جواز عقاري بعد. أكمل تقديراً لإنشاء أول جواز.':'Aucun Passeport pour le moment. Finalisez une estimation pour créer le premier.'}</CardSurface>:null}</>:null}
    {section==='compare'?<><h2 className="text-xl font-bold">{ar?'قارن عقاراتك وتقديراتك':'Comparez vos biens et estimations'}</h2><p className="text-sm text-text-secondary">{ar?'اختر عنصرين إلى ستة عناصر.':'Sélectionnez de deux à six éléments.'}</p><div className="grid gap-4 lg:grid-cols-2">{data.events.map((event:any)=>eventCard(event,true))}{data.properties.map((property:any)=><CardSurface key={property.id} className="p-5"><label className="flex min-h-11 items-center gap-3"><input type="checkbox" checked={selection.includes(`property:${property.id}`)} onChange={()=>toggle(`property:${property.id}`)}/>{property.label}</label><p className="text-sm text-text-secondary">{property.input_features.neighborhood} · {formatArea(property.input_features.area,locale)}</p></CardSurface>)}</div><button disabled={selection.length<2||busy} onClick={compare} className="min-h-11 rounded-control bg-brand-blue px-5 text-white disabled:opacity-50">{ar?'مقارنة':'Comparer'}</button>{comparison.length?<div className="overflow-x-auto rounded-card border border-border-medium"><table className="w-full text-start text-sm"><thead><tr><th className="p-4">{ar?'المعيار':'Critère'}</th>{comparison.map((item,index)=><th className="min-w-48 p-4" key={index}>{item.label||item.input_features.neighborhood}</th>)}</tr></thead><tbody>{[
      [ar?'المدينة':'Ville',(item:any)=>item.input_features.city], [ar?'الحي':'Quartier',(item:any)=>item.input_features.neighborhood], [ar?'النوع':'Type',(item:any)=>item.input_features.property_type], [ar?'المساحة':'Surface',(item:any)=>formatArea(item.input_features.area,locale)], [ar?'التقدير المحفوظ':'Estimation enregistrée',(item:any)=>item.estimated_price_mad?formatCurrency(Number(item.estimated_price_mad),locale):'—'], [ar?'درهم/م²':'MAD/m²',(item:any)=>item.estimated_price_mad?formatInteger(Number(item.estimated_price_mad)/item.input_features.area,locale):'—'],
    ].map(([label,get]:any)=><tr key={label} className="border-t border-border-subtle"><th className="p-4 text-start">{label}</th>{comparison.map((item,index)=><td key={index} className="p-4">{get(item)}</td>)}</tr>)}</tbody></table></div>:null}</>:null}
    {section==='profile'?<ProfileSettings locale={locale} data={data} refresh={load} logout={logout} busy={busy}/>:null}
    {['estimations','properties','passports','compare'].includes(section)?<div className="flex items-center gap-5"><button disabled={page===1} className="min-h-11 disabled:opacity-40" onClick={()=>setPage(p=>p-1)}>{ar?'السابق':'Précédent'}</button><span>{page}</span><button disabled={page*20>=Math.max(section==='properties'?0:data.eventCount,['estimations','passports'].includes(section)?0:data.propertyCount)} className="min-h-11 disabled:opacity-40" onClick={()=>setPage(p=>p+1)}>{ar?'التالي':'Suivant'}</button></div>:null}
  </div>;
}

function ProfileSettings({locale,data,refresh,logout,busy}:{locale:string;data:any;refresh:()=>Promise<void>;logout:(all?:boolean)=>Promise<void>;busy:boolean}){
  const ar=locale==='ar',[name,setName]=useState(data.profile.display_name||''),[saving,setSaving]=useState(false),[message,setMessage]=useState('');
  async function save(){setSaving(true);setMessage('');try{const response=await fetch('/api/account',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({display_name:name})});if(!response.ok)throw new Error();await refresh();setMessage(ar?'تم تحديث الاسم المعروض.':'Nom affiché mis à jour.');}catch{setMessage(ar?'تعذر تحديث الملف.':'Mise à jour du profil indisponible.');}finally{setSaving(false);}}
  return <CardSurface className="space-y-6 p-5 sm:p-6"><div><h2 className="text-xl font-bold">{ar?'الملف والإعدادات':'Profil et réglages'}</h2><p className="mt-2 text-sm text-text-secondary">{ar?'تحكم في هويتك العامة وأمان جلساتك.':'Gérez votre identité d’affichage et la sécurité de vos sessions.'}</p></div><label className="block text-sm font-semibold">{ar?'الاسم المعروض':'Nom affiché'}<input value={name} onChange={event=>setName(event.target.value)} maxLength={80} autoComplete="name" className="auth-input mt-2"/></label><button disabled={saving} onClick={save} className="min-h-11 rounded-control bg-brand-blue px-5 text-sm font-bold text-white disabled:opacity-50">{saving?(ar?'جارٍ الحفظ…':'Enregistrement…'):(ar?'حفظ الاسم':'Enregistrer le nom')}</button>{message?<p role="status" className="text-sm">{message}</p>:null}<div className="border-t border-border-subtle pt-5"><p className="text-sm font-semibold">{ar?'البريد الإلكتروني':'Adresse e-mail'}</p><p className="mt-1 text-sm text-text-secondary" dir="ltr">{data.email}</p><Link className="mt-3 inline-flex min-h-11 items-center text-sm font-semibold text-brand-blue" href={`/${locale}/auth/forgot-password`}>{ar?'تغيير كلمة المرور عبر البريد الإلكتروني':'Changer mon mot de passe par e-mail'}</Link></div><div className="flex flex-wrap gap-5 border-t border-border-subtle pt-5"><button disabled={busy} onClick={()=>logout()} className="min-h-11 text-sm font-semibold text-brand-blue">{ar?'تسجيل الخروج':'Déconnexion'}</button><button disabled={busy} onClick={()=>logout(true)} className="min-h-11 text-sm font-semibold text-brand-blue">{ar?'تسجيل الخروج من جميع الجلسات':'Déconnecter toutes mes sessions'}</button></div></CardSurface>;
}

function PropertyCard({property,locale,refresh}:{property:any;locale:string;refresh:()=>Promise<void>}){
  const ar=locale==='ar',[label,setLabel]=useState(property.label),[confirm,setConfirm]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  async function change(method:'PATCH'|'DELETE'){setBusy(true);setError('');try{const response=await fetch(`/api/account/properties/${property.id}`,{method,headers:{'Content-Type':'application/json'},body:method==='PATCH'?JSON.stringify({label}):undefined});if(!response.ok)throw new Error();await refresh();}catch{setError(ar?'تعذر حفظ التغيير.':'Modification indisponible.');}finally{setBusy(false);}}
  return <CardSurface className="p-5"><label className="text-sm">{ar?'اسم العقار':'Nom du bien'}<input value={label} onChange={event=>setLabel(event.target.value)} maxLength={100} className="mt-2 min-h-11 w-full rounded-control border border-border-medium bg-surface px-3"/></label><p className="mt-3 text-sm text-text-secondary">{property.city?.name} · {property.input_features.neighborhood} · {formatArea(property.input_features.area,locale)}</p><div className="mt-4 flex flex-wrap gap-4 text-sm text-brand-blue"><button disabled={busy||!label.trim()} className="min-h-11" onClick={()=>change('PATCH')}>{ar?'حفظ الاسم':'Enregistrer le nom'}</button><Link className="inline-flex min-h-11 items-center" href={`/${locale}/cities/casablanca/estimate?property=${property.id}`}>{ar?'إعادة التقدير':'Préremplir et réestimer'}</Link><button disabled={busy} className="min-h-11" onClick={()=>confirm?change('DELETE'):setConfirm(true)}>{confirm?(ar?'تأكيد الحذف':'Confirmer la suppression'):(ar?'حذف':'Supprimer')}</button></div>{error?<p role="alert">{error}</p>:null}</CardSurface>;
}
