'use client';

import { AlertTriangle, BarChart3, CheckCircle2, Database, Gauge, MapPinned, Rows3, ShieldCheck } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { formatArea, formatInteger, formatNumber } from '@/lib/utils';

const card = 'rounded-[22px] border border-slate-200/75 bg-white shadow-[0_12px_32px_-20px_rgba(15,23,42,.28)] dark:border-white/10 dark:bg-[#111c30]';
function Empty({ title, text }: { title: string; text: string }) { return <div className={`${card} border-dashed p-6`}><p className="font-bold text-slate-800 dark:text-white">{title}</p><p className="mt-2 text-sm leading-6 text-slate-400">{text}</p></div>; }
function Header({ eyebrow, title, text }: { eyebrow: string; title: string; text: string }) { return <header className="mb-6"><p className="text-[11px] font-extrabold uppercase tracking-[.18em] text-blue-700 dark:text-blue-300">{eyebrow}</p><h2 className="mt-2 text-2xl font-extrabold tracking-[-.035em] text-slate-950 sm:text-3xl dark:text-white">{title}</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500 dark:text-slate-400">{text}</p></header>; }
function Stat({ label, value, Icon }: { label: string; value: string; Icon: any }) { return <div className={`${card} p-4 sm:p-5`}><Icon className="h-5 w-5 text-blue-600"/><p className="mt-5 text-[10px] font-extrabold uppercase tracking-[.12em] text-slate-400">{label}</p><p className="mt-2 text-2xl font-extrabold tracking-[-.04em] text-slate-950 dark:text-white">{value}</p></div>; }

export function DataQualityPanel({ data, loading }: { data: any; loading: boolean }) {
  if (loading) return <Empty title="Analyse du référentiel…" text="Calcul des indicateurs réels de qualité et des distributions."/>;
  const q = data?.quality; if (!q) return <Empty title="Données analytiques indisponibles" text="Aucun référentiel analytique n’est configuré pour cette ville."/>;
  const missing = Object.entries(q.missingByField || {}) as Array<[string, number]>; const invalid = Object.entries(q.invalidByRule || {}) as Array<[string, number]>;
  return <><Header eyebrow="Reference Data Observatory" title="Données & Qualité" text="Audit calculé directement sur la version du référentiel Casablanca utilisée par le modèle approuvé. Aucune note de qualité artificielle n’est produite."/>
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Stat label="Lignes totales" value={formatInteger(q.totalRows)} Icon={Rows3}/><Stat label="Lignes utilisables" value={formatInteger(q.usableRows)} Icon={CheckCircle2}/><Stat label="Doublons exacts" value={formatInteger(q.duplicateRows)} Icon={Database}/><Stat label="Quartiers représentés" value={formatInteger(q.neighborhoodCoverage.distinct)} Icon={MapPinned}/></div>
    <div className="mt-5 grid gap-5 xl:grid-cols-2"><section className={`${card} p-5 sm:p-6`}><h3 className="font-extrabold text-slate-900 dark:text-white">Valeurs manquantes</h3><p className="mt-1 text-xs text-slate-400">Comptage brut par colonne du CSV de référence</p><div className="mt-5 grid grid-cols-2 gap-2">{missing.map(([field,count])=><div key={field} className="flex justify-between rounded-xl bg-slate-50 px-3 py-2.5 text-xs dark:bg-white/[.035]"><span>{field}</span><b>{formatInteger(count)}</b></div>)}</div></section>
      <section className={`${card} p-5 sm:p-6`}><h3 className="font-extrabold text-slate-900 dark:text-white">Contrôles de validité</h3><p className="mt-1 text-xs text-slate-400">Règles cohérentes avec les limites logiques du prétraitement approuvé</p><div className="mt-5 space-y-2">{invalid.map(([rule,count])=><div key={rule} className="flex justify-between rounded-xl bg-slate-50 px-3 py-2.5 text-xs dark:bg-white/[.035]"><span>{rule}</span><b className={count?'text-amber-700':'text-emerald-700'}>{formatInteger(count)}</b></div>)}</div></section></div>
    <section className={`${card} mt-5 p-5 sm:p-6`}><h3 className="font-extrabold text-slate-900 dark:text-white">Distribution des entrées numériques</h3><p className="mt-1 text-xs text-slate-400">Référence descriptive P5–P95, médiane et étendue; aucune modification du prétraitement.</p><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[700px] text-left text-xs"><thead className="text-[9px] uppercase tracking-wider text-slate-400"><tr>{['Champ','N','Minimum','P5','Médiane','P95','Maximum','Moyenne'].map((label)=><th key={label} className="px-3 py-3">{label}</th>)}</tr></thead><tbody>{q.referenceDistributions.numeric.map((item:any)=><tr key={item.field} className="border-t border-slate-100 dark:border-white/10"><td className="px-3 py-3 font-bold">{item.field}</td>{[item.count,item.min,item.q05,item.median,item.q95,item.max,item.mean].map((value,index)=><td key={index} className="px-3 py-3">{formatNumber(value)}</td>)}</tr>)}</tbody></table></div></section>
    <div className="mt-5 grid gap-5 xl:grid-cols-2"><section className={`${card} p-5 sm:p-6`}><h3 className="font-extrabold">Couverture des types de biens</h3><div className="mt-5 h-64"><ResponsiveContainer><BarChart data={q.propertyTypeCoverage}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="label" tick={{fontSize:10}}/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="count" fill="#2563eb" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></div></section><section className={`${card} p-5 sm:p-6`}><h3 className="font-extrabold">Couverture du manifeste</h3><dl className="mt-5 space-y-3"><div className="flex justify-between rounded-xl bg-slate-50 p-4 dark:bg-white/[.035]"><dt>Quartiers reconnus par le modèle</dt><dd className="font-bold">{formatInteger(q.neighborhoodCoverage.supportedByModel)}</dd></div><div className="flex justify-between rounded-xl bg-slate-50 p-4 dark:bg-white/[.035]"><dt>Hors manifeste</dt><dd className="font-bold">{formatInteger(q.neighborhoodCoverage.outsideModelManifest)}</dd></div></dl><p className="mt-5 text-xs leading-5 text-slate-400">Source unique : {q.dataset}</p></section></div>
  </>;
}

export function InputDriftPanel({ data, loading }: { data: any; loading: boolean }) {
  if (loading) return <Empty title="Chargement de la surveillance…" text="Comparaison des entrées réelles avec les distributions de référence."/>;
  const drift = data?.drift; if (!drift) return <Empty title="Surveillance indisponible" text="La ville ne fournit pas encore de référentiel compatible."/>;
  return <><Header eyebrow="Input Distribution Monitoring" title="Surveillance des entrées" text="Comparaison descriptive des estimations réelles non-test avec le référentiel Casablanca. Cette vue ne mesure pas la performance du modèle et ne suppose aucune baisse de précision."/>
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-3"><Stat label="Entrées de production" value={formatInteger(drift.productionCount)} Icon={Database}/><Stat label="Minimum requis" value={formatInteger(drift.minimumProductionObservations)} Icon={Gauge}/><Stat label="Méthodes" value="PSI · TVD" Icon={BarChart3}/></div>
    {!drift.sufficientData ? <div className="mt-5"><Empty title={drift.message || 'Données insuffisantes pour évaluer la dérive.'} text="Aucun résultat de dérive n’est généré avant que le seuil d’observations réelles soit atteint."/></div> : <section className={`${card} mt-5 overflow-hidden`}><div className="border-b border-slate-100 p-5 dark:border-white/10"><h3 className="font-extrabold">Signaux par variable</h3><p className="mt-1 text-xs text-slate-400">PSI : stable &lt; 0,10; vigilance 0,10–0,25; dérive ≥ 0,25. Distance de variation totale : stable &lt; 0,10; vigilance 0,10–0,20; dérive ≥ 0,20.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50 text-[9px] uppercase tracking-wider text-slate-400 dark:bg-white/[.025]"><tr>{['Variable','Méthode','Valeur','Référence','Production','État','Lecture'].map((label)=><th key={label} className="px-5 py-3">{label}</th>)}</tr></thead><tbody>{drift.features.map((feature:any)=><tr key={feature.field} className="border-t border-slate-100 dark:border-white/10"><td className="px-5 py-4 font-bold">{feature.field}</td><td className="px-5 py-4">{feature.method}</td><td className="px-5 py-4 font-bold">{formatNumber(feature.value,'fr',3)}</td><td className="px-5 py-4">{formatInteger(feature.referenceCount)}</td><td className="px-5 py-4">{formatInteger(feature.productionCount)}</td><td className="px-5 py-4"><span className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[10px] font-bold ${feature.status==='stable'?'bg-emerald-50 text-emerald-700':feature.status==='watch'?'bg-amber-50 text-amber-700':'bg-red-50 text-red-700'}`}>{feature.status==='stable'?<CheckCircle2 className="h-3 w-3"/>:<AlertTriangle className="h-3 w-3"/>}{feature.status}</span></td><td className="px-5 py-4 text-xs text-slate-400">{feature.detail || 'Comparaison de distribution'}</td></tr>)}</tbody></table></div></section>}
    <p className="mt-4 flex items-start gap-2 text-xs leading-5 text-slate-400"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0"/>Aucun « score de santé IA » n’est calculé. Sans prix de transaction observé après estimation, cette surveillance ne permet pas de conclure sur l’erreur ou la précision.</p>
  </>;
}
